export type SurgeryBlockId = 'TO1' | 'TO2' | 'TO3' | 'TO4';

export type SurgeryTopicDefinition = {
  id: string;
  block: SurgeryBlockId;
  number: number;
  title: string;
  titleIsPlaceholder: boolean;
};

export const SURGERY_EXAM_DATE = '2026-09-08';

// Official 2025-2026 titles, kept in one static source. Stable IDs remain the persistence keys.
const TITLES: Readonly<Record<SurgeryBlockId, readonly string[]>> = {
  TO1: [
    "Local anesthesia, regional anesthesia (peripheral nerve blocks, epidural and spinal anesthesia)",
    "Purulent infection of hand and fingers",
    "Sterilization, asepsis, disinfection, antisepsis",
    "Antibiotics in surgery",
    "Intravenous fluid therapy, fluid and electrolyte balance and disorders, types of intravenous fluids",
    "SSI – Surgical site infections: classification, prevention, diagnosis, treatment",
    "Purulent (non-necrotizing) infection of skin and soft tissues, diagnosis, treatment",
    "Necrotizing and anaerobic infections of skin and soft tissues, diagnosis, treatment",
    "Osteomyelitis",
    "Mass-casualty incidents, principles of triage and stages of management, the START system",
    "Pressure ulcers – classification, treatment",
    "Types of wounds – classification, characteristic, algorithm of treatment",
    "Wound healing",
    "Blood transfusion, indications, general principles, blood type systems, transfusion safety measures, administration of transfusions, complications",
    "Sepsis, Systemic Inflammatory Response Syndrome (SIRS), MODS",
    "Principles of cancer management",
    "Nutritional management and acid-base balance in the surgical patient",
    "Physical examination in surgery",
    "Principles of transplantation surgery",
    "General anesthesia – intravenous and inhalational anesthetics",
    "Preoperative assessment – patient fitness for surgery, risks of a surgical intervention, classification",
    "Legal aspects of surgical interventions",
    "Cricothyrotomy, tracheostomy (indication for intervention)",
    "Principles of postoperative care (recovery room, ICU)",
    "Thromboembolic disease – prevention of venous thromboembolism in surgery",
    "Cardiovascular and respiratory postoperative complications",
    "Gastrointestinal and urinary postoperative complications",
    "Thoracentesis and chest tube drainage",
    "Principles of plastic surgery",
    "Pathophysiology of shock, classification",
    "Shock - prevention and treatment",
    "Bleeding, classification, first aid, treatment",
    "Cardiopulmonary resuscitation",
    "Preoperative management – preoperative lifestyle modification, fasting and medical problems",
    "Present-day war injuries, injuries in terrorist attacks, characteristics and treatment",
    "Burns and frostbites",
    "Diagnostic methods in surgery - laboratory tests, imaging methods",
    "Nosocomial infection (healthcare-associated infections) – definition and classification",
    "Types of sutures in surgery, suture materials, staplers",
    "Operating theatre, operating room equipment, operating room staff, personal protective equipment",
  ],
  TO2: [
    "Definition and classification of acute abdomen",
    "Clinical manifestation of acute abdomen",
    "Abdominal pain in the right lower quadrant, differential diagnosis",
    "Abdominal pain in the epigastrium and right upper quadrant, differential diagnosis",
    "Abdominal pain in the left lower quadrant, differential diagnosis",
    "Obstructive jaundice",
    "Hematemesis, melena, hematochezia",
    "Pneumoperitoneum – etiology, diagnosis, therapy",
    "Non-traumatic hemoperitoneum – local and systemic causes",
    "Classification of intraabdominal infections",
    "Acute peritonitis, classification and principles of diagnosis and treatment",
    "Acute appendicitis",
    "Acute appendicitis in children",
    "Acute appendicitis: uncomplicated vs complicated course",
    "Atypical manifestation of acute appendicitis – etiology and clinical manifestation",
    "Acute cholecystitis, acute cholangitis",
    "Acute pancreatitis",
    "Acute diverticulitis, complications",
    "Subdiaphragmatic abscesses",
    "Classification and pathophysiology of bowel obstruction and bowel strangulation",
    "Mechanical bowel obstruction",
    "Incarcerated abdominal hernias",
    "Bowel volvulus and bowel intussusception",
    "Intestinal ischemia",
    "Paralytic ileus",
    "Upper GIT bleeding",
    "Lower GIT bleeding",
    "Classification of traumatic acute abdomen (penetrating and blunt trauma)",
    "Trauma of liver and spleen",
    "Cholelithiasis – symptomatology and complications",
    "Inguinal and femoral hernias",
    "Uncommon hernias – pelvic hernias, lateral abdominal wall hernias",
    "Ventral hernias (umbilical, supra-umbilical, incisional, parastomal)",
    "Chronic pancreatitis",
    "Surgery for peptic ulcer disease complications",
    "Ulcerative colitis, Crohn´s disease",
    "Anal abscess and fistula",
    "Anal fissures and hemorrhoids",
    "Pilonidal cyst – etiology, clinical manifestation, and treatment",
    "Hiatal hernia and GERD, esophageal achalasia",
    "Mediastinum – injuries, inflammation, tumors",
    "Pneumothorax, hemothorax, pleural effusion (pleural empyema, malignant pleural effusion)",
    "Lung trauma, complications of pneumonia, emphysema of the thorax",
    "Cysts and abscesses of the liver, benign liver tumors",
    "Goiter, classification. Thyrotoxicosis.",
    "Thyroid gland tumors",
    "Tumors of the esophagus",
    "Tumors of the stomach",
    "Malignant liver tumors",
    "Tumors and inflammation of the small intestine",
    "Tumors of the large intestine and rectum – screening, clinical manifestations, diagnosis",
    "Tumors of the bile duct and ampulla of Vater",
    "Tumors of the pancreas – clinical manifestation, treatment",
    "Neuroendocrine tumors of the GIT",
    "Malignant melanoma",
    "Sarcomas of soft tissues (in extremities and retroperitoneum)",
    "Tumors of the lung",
    "Tumors of the mammary gland – classification, screening, diagnosis, treatment",
    "Inflammations of the mammary gland – classification, differential diagnosis, treatment",
    "Hernias, phimosis and cryptorchidism in childhood",
    "Pyloric stenosis and intussusception in children",
    "Necrotizing enterocolitis in children",
    "Most common congenital development defects of the GIT in children",
    "Most common congenital development defects of the thorax in children (excluding heart defects)",
    "Appendectomy (laparoscopic and open)",
    "Cholecystectomy (laparoscopic and open)",
    "Colon and rectal surgery",
    "Stomas in the digestive tract",
    "Mini-invasive interventions in surgery (laparoscopy – diagnostic, therapeutic, types of operations; endoscopy; mini-invasive interventions in thoracic surgery – types)",
    "Bariatric and metabolic surgery",
    "Splenectomy, indications for splenectomy",
    "Surgery on the thyroid gland and parathyroid bodies, types of operations, risks, complications",
  ],
  TO3: [
    "Injury – definition, aetiology",
    "Polytrauma, classification, timing of therapeutic procedures – ATLS",
    "Crush syndrome, blast syndrome",
    "Craniocerebral trauma",
    "Classification of fractures",
    "Conservative (nonoperative) treatment of fractures",
    "Surgical (operative) treatment of fractures",
    "Open fractures – classification and principles of treatment",
    "Types of immobilizations – bandage, plaster cast, splints",
    "Compartment syndrome (extremity, abdominal)",
    "Fracture complications",
    "Pediatric fracture - characteristics and principles of treatment",
    "Soft tissue injury (skin, subcutaneous tissue, muscle, tendon, ligament)",
    "Joint injury",
    "Shoulder dislocation",
    "Clavicle fracture, scapula fracture, acromioclavicular joint injury",
    "Proximal humerus fracture",
    "Humeral shaft fracture",
    "Distal humerus fracture in children and adults",
    "Around elbow fractures, elbow dislocation",
    "Forearm fractures",
    "Distal radius fracture",
    "Fracture and dislocation of carpal and metacarpal bones. Finger fracture.",
    "Pelvic fracture - classification and treatment",
    "Hip fractures - classification and treatment",
    "Femoral shaft fracture",
    "Distal femoral fractures",
    "Knee ligaments injury, meniscus tears, osteochondritis dissecans",
    "Tibial plateau fracture, patella fractures, patellar dislocation",
    "Tibia and fibula shaft fractures",
    "Achilles tendon rupture",
    "Ankle fractures",
    "Ankle sprains",
    "Calcaneal fracture",
    "Metatarsal and phalangeal fractures",
    "Vertebral fractures - classification, diagnosis, treatment",
    "Cervical vertebrae fractures",
    "Ribs and sternum fractures",
    "Tendon and ligament injury of the hand",
  ],
  TO4: [
    "Tetralogy of Fallot",
    "Myocardial protection (during open heart surgery)",
    "Congenital ventricular septal defects",
    "Critical limb ischemia",
    "Aortic valve disease (acquired) and aortic valvule surgery",
    "Tricuspid valve disease (congenital, acquired), tricuspid valve surgery",
    "Vascular injuries",
    "Atrial septal defect, anomalous pulmonary venous return",
    "Chronic venous insufficiency - pathophysiology, symptoms, complications, treatment",
    "Transposition of the great arteries",
    "Thromboembolic disease",
    "Mechanical and biological arteficial valve prostheses",
    "Congenital malformation of the thoracis aorta",
    "Surgery of cardiac arrhythmias",
    "Pericardial disease and surgery",
    "Surgery of cerebrovascular insufficiency (symptomatic and asymptomatic stenosis of the carotid artery)",
    "Vascular reconstruction (anatomically and extraanatomically)",
    "Hypothermia in cardiovascular surgery",
    "Ischemia of visceral arteries (tr. coeliacus, a. mesenterica sup., a. renalis, aa.il.int.). Clinical manifestation and therapy.",
    "Aortoiliac atherosclerotic occlusive disease. Leriche syndrome.",
    "Peripheral artery disease, endovascular interventions and surgical procedures",
    "Vascular access for hemodialysis (A-V fistulas)",
    "Cardiac injury and great vessels trauma (blunt and penetrating injuries)",
    "Cardiac tamponade",
    "Surgery of ischemic heart disease",
    "Mechanical complications of myocardial infarction (papillary muscle rupture, ventricular septal rupture, free wall rupture, aneurysm of the left ventricle)",
    "Vascular complications of diabetes mellitus - surgical therapy.",
    "Heart transplantation",
    "Arterial aneurysm, clinical manifestation, diagnosis and treatment",
    "Infectious endocarditis",
    "Complications in vascular surgery (early thrombosis of the graft vessel, infection)",
    "Clinical examination in patients with vascular disease",
    "Abdominal aortic aneurysm (symptoms, diagnosis, therapy)",
    "Thoracic aortic aneurysm",
    "Mitral valve disease and surgery of the mitral valve",
    "Thoracic outlet syndrome",
    "Principle of extracorporeal circulation",
    "Congenital pulmonary artery anomalies",
    "Thoracic aortic dissection",
    "Mechanical heart support, ECMO",
    "Acute arterial occlusions (embolism, thrombosis)",
    "Pharmacotherapy in vascular surgery (antiplatelet agents, anticoagulants, vasodilatory drugs)",
    "Coarctation of the aorta, ductus arteriosus - Botallo duct (therapy)",
    "Endovascular interventions for arterial occlusions and stenoses",
    "Basic principles of vascular surgery, types of prostheses",
  ],
};

export const SURGERY_BLOCKS: ReadonlyArray<{ id: SurgeryBlockId; count: number; label: string }> = (
  Object.keys(TITLES) as SurgeryBlockId[]
).map((id) => ({
  id,
  count: TITLES[id].length,
  label: ({ TO1: 'General Surgery', TO2: 'Special Surgery', TO3: 'Traumatology', TO4: 'Cardiac & Vascular' } as const)[id]
}));

export const SURGERY_SYLLABUS: readonly SurgeryTopicDefinition[] = SURGERY_BLOCKS.flatMap(
  ({ id: block }) => TITLES[block].map((title, index) => {
    const number = index + 1;
    return { id: `${block}-${String(number).padStart(2, '0')}`, block, number, title, titleIsPlaceholder: false };
  })
);

export const SURGERY_TOPIC_IDS = new Set(SURGERY_SYLLABUS.map((topic) => topic.id));

