import test from 'node:test'; import assert from 'node:assert/strict';
import { validatePatch } from '../src/lib/study/surgerySchema.ts';
import { applyExplicitPlanPatch } from '../src/lib/study/studyPlanPatch.ts';

const now='2026-08-14T12:56:00.000Z';
const progress=()=>({schemaVersion:1,initializedAt:now,baselineCapturedAt:now,baselineFirstPassCount:0,updatedAt:now,topics:{'TO1-02':{},'TO1-08':{},'TO1-09':{},'TO1-10':{}}});

test('assessment without plan metadata never completes first pass',()=>{const patch=validatePatch({schemaVersion:1,topics:[{id:'TO1-08',mastery:2,attemptsDelta:1}],session:{date:now,label:'One vignette',questions:1}});const result=applyExplicitPlanPatch(progress(),patch,now,'s1');assert.equal(result.changed,false);assert.equal(result.progress.topics['TO1-08'].firstPassCompletedAt,undefined)});
test('explicit first-pass flag completes exactly one topic with requested timestamp',()=>{const patch=validatePatch({schemaVersion:1,topics:[{id:'TO1-02',mastery:2,attemptsDelta:7,plan:{firstPassComplete:true,firstPassCompletedAt:now}}],session:{questions:7}});const result=applyExplicitPlanPatch(progress(),patch,now,'s2');assert.equal(result.changed,true);assert.equal(result.progress.topics['TO1-02'].firstPassCompletedAt,now);assert.equal(Object.values(result.progress.topics).filter(t=>t.firstPassCompletedAt).length,1);assert.equal(result.progress.topics['TO1-02'].secondPassCompletedAt,undefined)});
test('isolated questions across topics complete zero without flags',()=>{const patch=validatePatch({schemaVersion:1,topics:['TO1-02','TO1-08','TO1-09','TO1-10'].map(id=>({id,attemptsDelta:1,mastery:2})),session:{questions:4,mode:'multiple-choice'}});const result=applyExplicitPlanPatch(progress(),patch,now);assert.equal(Object.values(result.progress.topics).filter(t=>t.firstPassCompletedAt).length,0)});
test('later assessment does not overwrite original completion timestamp',()=>{const p=progress();p.topics['TO1-02'].firstPassCompletedAt=now;const later='2026-08-16T10:00:00.000Z',patch=validatePatch({schemaVersion:1,topics:[{id:'TO1-02',attemptsDelta:2,plan:{firstPassComplete:true}}],session:{date:later,questions:2}});assert.equal(applyExplicitPlanPatch(p,patch,later).progress.topics['TO1-02'].firstPassCompletedAt,now)});
test('explicit false clears active completion but retains an audit event',()=>{const p=progress();p.topics['TO1-02']={firstPassCompletedAt:now,firstPassSource:'assistant'};const patch=validatePatch({schemaVersion:1,topics:[{id:'TO1-02',plan:{firstPassComplete:false}}]});const result=applyExplicitPlanPatch(p,patch,'2026-08-15T10:00:00.000Z');assert.equal(result.progress.topics['TO1-02'].firstPassCompletedAt,undefined);assert.equal(result.progress.topics['TO1-02'].completionHistory.at(-1).previousCompletedAt,now)});
test('legacy schemaVersion 1 patch remains valid and metadata-free',()=>{const patch=validatePatch({schemaVersion:1,topics:[{id:'TO1-08',mastery:4}],session:{date:now,label:'Legacy',questions:1}});assert.equal(patch.topics[0].plan,undefined);assert.equal(patch.session.mode,undefined)});
