import test from 'node:test'; import assert from 'node:assert/strict';
import { buildSchedule, forecast, pacing, passCount, phaseForDate, phaseForProgress } from '../src/lib/study/studyPlanEngine.ts';

const ids=Array.from({length:196},(_,i)=>`T-${i+1}`);
const config={schemaVersion:1,name:'Surgery',examDate:'2026-09-08',planStartDate:'2026-08-14',topicIds:ids,phases:[{id:'p1',name:'First',startDate:'2026-08-14',endDate:'2026-08-27',type:'first-pass',target:196,usesDailyPacing:true,includedBlocks:['TO1','TO2','TO3','TO4'],notes:''},{id:'p2',name:'Second',startDate:'2026-08-28',endDate:'2026-09-04',type:'second-pass',target:196,usesDailyPacing:true,includedBlocks:['TO1'],notes:''},{id:'p3',name:'Buffer',startDate:'2026-09-05',endDate:'2026-09-07',type:'buffer',target:0,usesDailyPacing:false,includedBlocks:[],notes:''}],dayOverrides:[],bufferObjectives:[],forecastWindowDays:5,createdAt:'',updatedAt:'',history:[]};
function progress(first=40){return {schemaVersion:1,initializedAt:'',baselineCapturedAt:'',baselineFirstPassCount:first,updatedAt:'',topics:Object.fromEntries(ids.map((id,i)=>[id,i<first?{firstPassCompletedAt:'2026-08-13T12:00:00Z'}:{}]))};}

test('196 topics with 40 baseline leaves 156 and reaches exactly 196',()=>{const p=progress();assert.equal(passCount(p,'first'),40);const s=buildSchedule(config,p,config.phases[0]);assert.equal(s.reduce((n,d)=>n+d.quota,0),156);assert.equal(s.at(-1).cumulativeTarget,196)});
test('off day gets zero and redistributes exact workload',()=>{const c=structuredClone(config);c.dayOverrides=[{date:'2026-08-15',weight:0}];const s=buildSchedule(c,progress(),c.phases[0]);assert.equal(s.find(d=>d.date==='2026-08-15').quota,0);assert.equal(s.reduce((n,d)=>n+d.quota,0),156)});
test('ahead, on-track and behind use start-of-day boundary',()=>{const p=progress(),phase=config.phases[0];let x=pacing(config,p,phase,'2026-08-14');assert.equal(x.status,'on-track');for(let i=40;i<60;i++)p.topics[ids[i]].firstPassCompletedAt='2026-08-14T18:00:00Z';x=pacing(config,p,phase,'2026-08-14');assert.equal(x.status,'ahead');const late=pacing(config,progress(),phase,'2026-08-16');assert.equal(late.status,'behind')});
test('phase boundaries transition through buffer and exam',()=>{assert.equal(phaseForDate(config,'2026-08-27').type,'first-pass');assert.equal(phaseForDate(config,'2026-08-28').type,'second-pass');assert.equal(phaseForDate(config,'2026-09-05').type,'buffer');assert.equal(phaseForDate(config,'2026-09-08'),undefined)});
test('operational phase remains first pass after its deadline until all topics are complete',()=>{const p=progress(151),phase=phaseForProgress(config,p,'2026-08-28');assert.equal(phase.type,'first-pass');const pace=pacing(config,p,phase,'2026-08-28');assert.equal(pace.status,'behind');assert.ok(pace.todayQuota>0);assert.equal(pace.remaining,45)});
test('overdue daily goal dynamically redistributes the start-of-day backlog',()=>{const p=progress(145);p.topics[ids[145]].firstPassCompletedAt='2026-08-28T09:00:00Z';p.topics[ids[146]].firstPassCompletedAt='2026-08-28T10:00:00Z';const pace=pacing(config,p,config.phases[0],'2026-08-28');assert.equal(pace.todayActual,2);assert.equal(pace.todayQuota,5);assert.equal(pace.todayRemaining,3);assert.equal(pace.requiredPace,49/11)});
test('second pass unlocks only after first-pass target is complete and runs through the last pre-exam day',()=>{const p=progress(196);const phase=phaseForProgress(config,p,'2026-08-28');assert.equal(phase.type,'second-pass');assert.equal(phase.endDate,'2026-09-07');p.topics[ids[0]].secondPassCompletedAt='2026-08-28T18:00:00Z';assert.equal(phaseForProgress(config,p,'2026-08-29').type,'second-pass')});
test('buffer does not replace an unfinished second pass',()=>{const p=progress(196);assert.equal(phaseForProgress(config,p,'2026-09-05').type,'second-pass')});
test('editing deadline recalculates without mutating completions',()=>{const p=progress();const stamp=p.topics[ids[0]].firstPassCompletedAt,c=structuredClone(config);c.phases[0].endDate='2026-08-29';assert.equal(buildSchedule(c,p,c.phases[0]).length,16);assert.equal(p.topics[ids[0]].firstPassCompletedAt,stamp)});
test('forecast reports an honest date after the exam instead of clamping to exam day',()=>{const p=progress(196);for(let i=0;i<19;i++)p.topics[ids[i]].secondPassCompletedAt=`2026-09-${String(i<10?1:2).padStart(2,'0')}T12:00:00Z`;const result=forecast(config,p,config.phases[1],'2026-09-02');assert.ok(result);assert.equal(result.pace,9.5);assert.equal(result.date,'2026-09-21');assert.ok(result.date>config.examDate)});
test('second-pass daily denominator rebases from remaining work through 7 September',()=>{const p=progress(196);for(let i=0;i<19;i++)p.topics[ids[i]].secondPassCompletedAt='2026-09-01T12:00:00Z';const phase=phaseForProgress(config,p,'2026-09-02');const pace=pacing(config,p,phase,'2026-09-02');assert.equal(phase.endDate,'2026-09-07');assert.equal(pace.todayQuota,30);for(let i=19;i<29;i++)p.topics[ids[i]].secondPassCompletedAt='2026-09-02T12:00:00Z';assert.equal(pacing(config,p,phase,'2026-09-02').todayQuota,30)});
