import test from 'node:test'; import assert from 'node:assert/strict';
import { buildSchedule, pacing, passCount, phaseForDate } from '../src/lib/study/studyPlanEngine.ts';

const ids=Array.from({length:196},(_,i)=>`T-${i+1}`);
const config={schemaVersion:1,name:'Surgery',examDate:'2026-09-08',planStartDate:'2026-08-14',topicIds:ids,phases:[{id:'p1',name:'First',startDate:'2026-08-14',endDate:'2026-08-27',type:'first-pass',target:196,usesDailyPacing:true,includedBlocks:['TO1','TO2','TO3','TO4'],notes:''},{id:'p2',name:'Second',startDate:'2026-08-28',endDate:'2026-09-04',type:'second-pass',target:196,usesDailyPacing:true,includedBlocks:['TO1'],notes:''},{id:'p3',name:'Buffer',startDate:'2026-09-05',endDate:'2026-09-07',type:'buffer',target:0,usesDailyPacing:false,includedBlocks:[],notes:''}],dayOverrides:[],bufferObjectives:[],forecastWindowDays:5,createdAt:'',updatedAt:'',history:[]};
function progress(first=40){return {schemaVersion:1,initializedAt:'',baselineCapturedAt:'',baselineFirstPassCount:first,updatedAt:'',topics:Object.fromEntries(ids.map((id,i)=>[id,i<first?{firstPassCompletedAt:'2026-08-13T12:00:00Z'}:{}]))};}

test('196 topics with 40 baseline leaves 156 and reaches exactly 196',()=>{const p=progress();assert.equal(passCount(p,'first'),40);const s=buildSchedule(config,p,config.phases[0]);assert.equal(s.reduce((n,d)=>n+d.quota,0),156);assert.equal(s.at(-1).cumulativeTarget,196)});
test('off day gets zero and redistributes exact workload',()=>{const c=structuredClone(config);c.dayOverrides=[{date:'2026-08-15',weight:0}];const s=buildSchedule(c,progress(),c.phases[0]);assert.equal(s.find(d=>d.date==='2026-08-15').quota,0);assert.equal(s.reduce((n,d)=>n+d.quota,0),156)});
test('ahead, on-track and behind use start-of-day boundary',()=>{const p=progress(),phase=config.phases[0];let x=pacing(config,p,phase,'2026-08-14');assert.equal(x.status,'on-track');for(let i=40;i<60;i++)p.topics[ids[i]].firstPassCompletedAt='2026-08-14T18:00:00Z';x=pacing(config,p,phase,'2026-08-14');assert.equal(x.status,'ahead');const late=pacing(config,progress(),phase,'2026-08-16');assert.equal(late.status,'behind')});
test('phase boundaries transition through buffer and exam',()=>{assert.equal(phaseForDate(config,'2026-08-27').type,'first-pass');assert.equal(phaseForDate(config,'2026-08-28').type,'second-pass');assert.equal(phaseForDate(config,'2026-09-05').type,'buffer');assert.equal(phaseForDate(config,'2026-09-08'),undefined)});
test('editing deadline recalculates without mutating completions',()=>{const p=progress();const stamp=p.topics[ids[0]].firstPassCompletedAt,c=structuredClone(config);c.phases[0].endDate='2026-08-29';assert.equal(buildSchedule(c,p,c.phases[0]).length,16);assert.equal(p.topics[ids[0]].firstPassCompletedAt,stamp)});
