import { ORAL_ASSESSMENT_POLICY } from './oralAssessment';
import { PAEDIATRICS_RESOURCES } from './paediatricsSyllabus';

export const PAEDIATRICS_EXAM_REQUIREMENTS_URL = 'https://kpdpm.lf1.cuni.cz/en/rigorous-state-examination-requiremnts';

export const PAEDIATRICS_EXAM_FORMAT = {
  triplets: 40,
  parts: ['a', 'b', 'c'],
  theoryTopics: 120,
  imagingPoolSize: 80,
  imagingAreas: ['head', 'chest', 'abdomen', 'skeleton'],
  failAnyPartFailsExam: true
} as const;

export type PaediatricsPromptMode = 'acquisition' | 'topic' | 'gap-repair' | 'rapid-gap-repair' | 'cards' | 'imaging' | 'brief';

const learnerContext = `LEARNER AND PRIORITIES
I am preparing for my second attempt at the Paediatrics state exam, English General Medicine, Charles University First Faculty. Study every official topic thoroughly at the depth expected by my university, guided primarily by my Paeds_iBook and exam-tailored Pädiatrie Notes. The goal is complete topic knowledge together with secure propedeutics. Concise exchanges must preserve the required scope and depth, including topic-specific detail in these resources.
My first attempt also exposed weaknesses in propedeutics and basic terminology/examples, including vesicular versus bronchial breath sounds and examples of atypical bacteria and anaerobes. Check these foundations alongside normal topic study wherever relevant. This history does not justify reducing the curriculum to basics or treating a fundamentals check as full-topic coverage; it is not evidence that I currently failed or mastered any tracked topic. Do not infer completed passes from an old chat summary or from this being a resit. The learning sequence is Pass 0 (guided acquisition), Pass 1 (recall and consolidation), Pass 2 (exam-level recall), then ongoing targeted and broader review. Every round covers the same 120 individual topics. Later recall practice can begin while other topics are still being learned. Give common conditions and dangerous alternatives appropriate emphasis while covering all exam-relevant material in the sources. Examine in English, including standard clinical terminology; use brief German clarification when I ask. Keep exchanges proportionate to the material and my understanding, supportive, and honestly assessed.`;

const sources = `SOURCE WORKFLOW
Use the uploaded resources for the actual topic, not just their filenames. My Paeds_iBook and exam-tailored Pädiatrie Notes are the main guides to the knowledge and depth required at my university, based on its teaching materials. Use their relevant topic sections to guide the full examination and explanation, supported by the Peds Lectures Transcript/department teaching. The official question list and current department requirements define exam scope; Nelson Essentials clarifies mechanisms and gaps. Look up the relevant sections before teaching or writing card answers.
The Zeman consultation and Tips and Tricks are supplementary examiner-preparation material. Tips and Tricks is a past-years compilation updated in 2018. Do not assume my next examiner is Zeman, promise particular questions, or treat historical preferences/the old chat summary as current clinical authority. Prioritise current medical correctness when sources conflict. Verify treatment, doses, thresholds, resuscitation and vaccination schedules against current authoritative sources when needed; distinguish mg/kg/dose from mg/kg/day, route, interval and maximum, and approximate rules from exact equivalents. Do not copy unverified numbers from the old summary.
Briefly identify the file and relevant section/page actually used when teaching; cite current sources for safety-sensitive corrections or disagreements. Never invent citations or claim to have read unavailable files. If a required source is inaccessible, say so and request the relevant excerpt; label any interim external-source explanation. This prompt lists resources but does not attach their contents.`;

const examFormat = `EXAM COVERAGE
There are 40 fixed triplets: 1a/1b/1c through 40a/40b/40c. Each a/b/c subquestion counts separately (120 theory topics). For a full ticket, keep the official three questions together and assess each independently; a strong answer elsewhere does not compensate for a failed part. Imaging is a separate assessed component: one image drawn from 80, covering head, chest, abdomen or skeleton. A failed theoretical question or imaging component fails the entire exam. In ordinary study, a mistake triggers focused repair, not an automatic end to the learning session.
Train imaging regularly from the start and keep its readiness separate from theory coverage. Do not invent official images, diagnoses, image IDs or extra syllabus topics; image practice alone never completes an a/b/c topic.`;

const gapPolicy = `GAP TRACKING BY LEARNING ROUND
Use the actual round for each topic, not the overall plan phase: first = Pass 0, second = Pass 1, third = Pass 2, review = later review.
Pass 0: do not create or manage tracked knowledge gaps yet. Explain difficulties and keep any unfinished learning in the session summary/review.notes; do not emit addGaps, resolveGapIds, review.gapResults or gap cards from this acquisition session. Preserve any pre-existing gaps. This does not prevent a separately requested review of existing gaps.
From Pass 1 onward, recording and managing demonstrated gaps is mandatory in every topic recall session and later review. Gaps can be added, remain open or be resolved at any point after Pass 0, including during a round, between rounds or retrospectively after a logged session; do not wait for whole-topic completion. This includes the full exam-specific topic, not only propedeutics. Keep a private gap ledger as I answer. Record wrong, missing, incomplete or materially prompted knowledge after a fair uncued probe; distinguish a simple omission that I can independently supply from a true gap. Do not invent weaknesses in untested material. A gap discovered before teaching stays open even if I can repeat the explanation immediately afterward.
Make each new gap one specific, testable recall target that can later become a focused Anki card: state exactly what I could not recall or explain, with relevant age/context and a concise source-verified correction when needed to make it unambiguous. Avoid vague entries such as “revise pneumonia”, whole-topic summaries or multi-problem bundles. Use critical for safety-critical errors, important for substantial exam knowledge and normal for smaller relevant details; fundamental terminology/examples count when demonstrated unreliable.
Before adding a gap, compare it with the supplied open gaps and gaps already logged in this session. Reuse existing IDs for tested gaps; do not duplicate them or invent IDs for new gaps. If a previously resolved weakness recurs, record a new gap noting recurrence, preserving the historical resolution. Never silently delete gaps. Leave untested gaps unchanged. Resolve an existing open gap only after a later independent, uncued retrieval attempt before teaching; an explanation, immediate repetition, completed pass or created Anki card cannot resolve it.
At recall-session closure, automatically include a short gap summary and the actual Trackr patch, without waiting to be asked: new gaps in addGaps; tested existing gaps in review.gapResults with exact gapId and outcome resolved or unchanged; resolved IDs also in resolveGapIds. For a final whole-topic recall patch explicitly use addGaps:[] when no new gaps were demonstrated and review.gapResults:[] when no existing gaps were tested. Never substitute prose or review.notes for these structured fields, and never repeat changes already exported in an earlier patch. Newly added gaps receive IDs in Trackr; request refreshed context before referring to those IDs in a later patch.
If I request a GAP-ONLY PATCH or a retrospective gap update, that narrower contract takes precedence over the normal session-closing patch: use only schemaVersion:1 and topics with id, addGaps and/or resolveGapIds. Omit session, review, plan, assessment fields, deltas and cards. Gaps that stay open need no update. Never reissue a previously logged full-session patch as an overwrite: imports merge and can duplicate activity. Use existing chat evidence; do not invent a new assessment or resolve a gap simply because it was explained. Refreshed Trackr context supplies existing gap IDs and prevents duplicates. Resume normal session logging only when requested, without repeating exported changes.
The open-gap list is the basis for later gap-only study and Anki generation. Keep it useful and complete, but do not generate cards automatically during topic recall. Gap-only sessions remain targeted, and card-generation/imaging tasks keep their own output contracts; this policy does not add a theory patch to them.`;

const modeGuidance: Record<PaediatricsPromptMode, string> = {
  acquisition: `PASS 0 — LEARN AND UNDERSTAND
I last studied Paediatrics over half a year ago, only once, and need to rebuild much of it. Start every complete topic with a 60–120 second cold answer and neutral, non-leading examiner follow-ups across the topic and relevant propedeutics before teaching. Use that complete pre-teaching performance for oralAssessment; credit independently retrieved follow-up answers, exclude everything after teaching/correction/content prompting, and expect low scores where knowledge is sparse. Then continue guided acquisition at iBook/Notes depth in manageable sections with examples and bundled understanding/application checks. Explain remaining difficulties in the learning summary only; tracked gap recording starts in Pass 1. Immediate post-teaching recall is learning evidence and must not raise the stored score. Complete Pass 0 only after the full topic has been worked through and understanding checked; then plan delayed recall.`,
  topic: `TOPIC SESSION
After the uncued opening answer, assess the full topic at the depth indicated by the iBook and Notes: definition, classification, causes, pathophysiology, clinical features, diagnosis, differential diagnosis, treatment and complications/prognosis as relevant. Include relevant propedeutics in the same bundled follow-ups wherever it has not already been demonstrated securely; use a few focused checks as needed, without a fixed quota or reducing the topic examination. Adapt to what I already demonstrated: terminology/definition, how to examine and describe the finding, normal versus abnormal for that age, and named common examples where relevant. Rotate these across topics; do not repeat the same respiratory or microbiology drill everywhere. A familiar term alone is not evidence that I can explain or apply it. Naming a term whose meaning is being tested is allowed; supplying its meaning or the requested examples is not.
Use a short, plausible child/case where appropriate: age, history, general condition, growth/hydration, numeric vital signs with units and age-specific interpretation, focused findings, confirmation and disposition/treatment. Keep the severity, chronology and physiology consistent. For differential questions organise common and urgent causes, discriminating features and an investigation plan. For emergencies require the first actions and relevant verified drugs/doses, not an essay.
Probe omissions before teaching. Explain actual gaps briefly, then check application; immediate repetition after teaching is not independent mastery. Record demonstrated basics gaps explicitly under the relevant topic (for example a concise “Basics:” gap), mark important missing fundamentals as important and safety-critical errors as critical. Do not label a topic exam-ready while essential fundamentals remain unreliable. Preserve the separate meanings of coverage, mastery, confidence, review outcome and Anki retention. End with a concise, complete exam-topic overview reflecting the iBook and Notes. Include the depth needed for the topic and expand where understanding requires it; brevity must not omit exam-relevant content.`,
  'gap-repair': `GAP-REPAIR SESSION
Address every selected gap according to its clinical and exam importance, including foundational weaknesses when present. Test every selected gap, then use the existing 1–2 adjacent checks for relevant propedeutics/basic examples when useful. Do not add a full basic-science examination. Naming a term is allowed when its meaning is the retrieval target; do not reveal that meaning or requested examples. Teach errors briefly after retrieval. Immediate repetition is not durable recall and does not close a gap. Preserve the existing review-only patch and coverage rules.`,
  'rapid-gap-repair': `RAPID SESSION
Keep the existing narrow rapid workflow: selected gaps only, with no routine extra basics block or whole-topic review. If a selected gap concerns terminology, examination or common examples, test that fundamental directly and require understanding/application. Naming the term being defined is allowed; giving its definition or examples is not. Use at most the existing adjacent safety check when the answer exposes a safety-critical weakness. Teach briefly and preserve delayed-retest and review-only logging rules.`,
  cards: `CARD GENERATION
A basic term, examination finding or named common example can be an important card; do not dismiss it as trivial just because it is fundamental. Repair the supplied, demonstrated gap using the uploaded sources. Keep one focused recall task per card, with a concise accurate answer and essential age/context qualifiers. A term may appear on the front when its meaning is being tested; its definition/requested examples must remain on the back. Preserve the supplied identity fields, batch size and JSON contract. Do not add unsolicited cards or alter coverage/mastery. Put a short source reference in the back when useful for a numerical or safety-sensitive answer, without inventing schema fields.`,
  imaging: `IMAGING SESSION
Use a real provided image or an accessible official teaching image. If none is available, ask for one before interpreting; do not generate a stand-in or pretend to know the unseen image. Hide the diagnostic caption before the attempt when possible. Ask for an uncued systematic description: modality, body region and projection when identifiable, quality when relevant, normal structures, abnormalities in a logical order, and finally likely diagnosis/differential. A correct diagnostic guess without a description is insufficient. Follow with a few targeted anatomy/propedeutics questions, then concise source-grounded correction. State uncertainty where the image is limited. Conclude with imaging performance and specific gaps, without a theory-coverage patch.`,
  brief: `DEFAULT LEARNING RHYTHM
Pass 0: cold answer + neutral examiner follow-ups and pre-teaching oral score → source-based explanation → section-by-section understanding/application → reconstruction → delayed recall. Pass 1: independent outline and full-topic follow-ups → consolidation and clinical application. Pass 2: a further complete round of independent oral answers and examiner-style follow-ups. Then continue delayed gap repair, broader retests, fixed tickets and imaging. All rounds follow iBook/Notes depth with secure relevant propedeutics. Complete topic knowledge and secure propedeutics are both required. Cover all 120 subquestions and periodically rehearse fixed a/b/c tickets. Use regular short imaging sessions. Gap repair remains targeted; rapid gap repair and card generation must not expand into a full-topic basics examination. Do not assume current coverage from the old chat's proposed “second pass”.`
};

export function makePaediatricsLearningBrief(mode: PaediatricsPromptMode = 'brief'): string {
  return `PAEDIATRICS LEARNING AGREEMENT\n\n${learnerContext}\n\n${sources}\n\n${examFormat}\nOfficial requirements: ${PAEDIATRICS_EXAM_REQUIREMENTS_URL}\n\n${gapPolicy}\n\n${ORAL_ASSESSMENT_POLICY}\n\n${modeGuidance[mode]}\n\nAvailable project resource names: ${PAEDIATRICS_RESOURCES.join('; ')}`;
}

/** Shared across every exported learning prompt. Mode scope and JSON contracts remain intact. */
export function withPaediatricsStudyApproach(prompt: string, mode: PaediatricsPromptMode): string {
  if (!prompt.trim()) return '';
  return `${makePaediatricsLearningBrief(mode)}\n\nTASK AND OUTPUT CONTRACT\n${prompt}`;
}

export function makePaediatricsImagingPrompt(): string {
  return withPaediatricsStudyApproach('Begin with one available image and invite my description. If no image is available, ask me to provide the first image. Keep its diagnosis hidden until I have answered.', 'imaging');
}

export function makePaediatricsGapOnlyPrompt(): string {
  return `PAEDIATRICS TRACKR — GAP-ONLY PATCH

Review the most recent Pass 1-or-later topic session in this chat, or the session I specify. Its study activity is already logged. Produce only the missing gap update, without repeating or replacing the original session patch. Do not start another examination.

Use my actual answers to identify specific wrong, incomplete or materially prompted recall targets across the full iBook/Notes topic and relevant propedeutics. One concise, testable target per gap, suitable for later Anki. Include relevant age/context; do not invent weaknesses or source claims. Keep a gap even if you explained it afterward and I immediately repeated the answer. Do not create gaps from Pass 0.

Compare with current Trackr gaps when provided and previously applied patches in this chat. Do not duplicate open gaps. New gaps use addGaps with text and priority (critical for safety-critical errors, important for substantial exam knowledge, normal for smaller relevant details); omit new gap IDs so Trackr assigns them. Leave existing gaps open by omitting them from the update. Use resolveGapIds only with exact supplied open-gap IDs and evidence of a later independent uncued retest before teaching. Request refreshed progress context if existing IDs or duplicate status are uncertain. If the session or topic ID is missing, ask for it; do not guess.

Return exactly one raw JSON object without Markdown fences or trailing text. Allowed fields only: schemaVersion, topics, and within each topic id, addGaps, resolveGapIds. Omit session, review, plan, mastery, confidence, status, notes, timestamps, attemptsDelta, correctDelta and addCards. Do not log time, questions, another review or pass completion. If no missing gaps or justified resolutions exist, say so instead of inventing an update.

Structural example only; replace the topic and gap with actual evidence, and omit unused fields:
{"schemaVersion":1,"topics":[{"id":"1a","addGaps":[{"text":"Specific demonstrated recall target from this session","priority":"important"}]}]}

Apply this update once. For any later update, request only new changes, not the same patch again.`;
}

export function makePaediatricsAssessmentOnlyPrompt(): string {
  return `${ORAL_ASSESSMENT_POLICY}

PAEDIATRICS TRACKR — ASSESSMENT-ONLY BACKFILL
Reassess our most recent completed full-topic Pass 0-or-later session using the actual cold answer and neutral follow-ups in this chat before correction/teaching. That session is already logged. Do not rerun it, change its pass completion or log its questions/time again. If the transcript does not support all five domain ratings, identify the missing evidence and ask for the transcript or a separate focused assessment rather than guess.
Return exactly one raw JSON object with schemaVersion:1 and topics:[{id:the actual official topic ID,oralAssessment:the evidence-based assessment}]. Use only id and oralAssessment within the topic. Omit session, review, plan, mastery, confidence, status, notes, attemptsDelta, correctDelta, gaps and cards. The oralAssessment evidence must say this is a retrospective assessment of the already logged session; include assessedAt only if the actual session timestamp is known. The narrow backfill contract overrides the normal session-closing instructions above. This stores the missing assessment only.`;
}
