<script lang="ts">
  import { onDestroy } from 'svelte';
  import { user, userReady } from '$lib/stores/user';
  import { readSurgeryArchive, clearSurgeryArchive, type SurgeryArchive } from '$lib/study/surgeryArchive';
  import { SURGERY_SYLLABUS, SURGERY_BLOCKS } from '$lib/study/surgerySyllabus';
  import { passCount } from '$lib/study/studyPlanEngine';
  import { groupSurgerySessionsByDay } from '$lib/study/surgeryChart';
  import { formatStudyDuration, timerElapsedSeconds } from '$lib/study/studyTimer';
  import SurgeryProgressChart from '$lib/components/SurgeryProgressChart.svelte';
  import AnkiStatsPanel from '$lib/components/AnkiStatsPanel.svelte';
  import { summarizeAnkiGapCards } from '$lib/study/ankiGapStats';
  let archive:SurgeryArchive|null=null, loading=true, error='', loadedUid='', search='', block='all', tab='topics';
  let request=0;
  $: uid=$user?.uid as string|undefined;
  $: if($userReady&&uid&&uid!==loadedUid)load(uid);
  $: if($userReady&&!uid){request+=1;loadedUid='';archive=null;loading=false;clearSurgeryArchive();}
  async function load(id:string){const token=++request;loadedUid=id;loading=true;archive=null;error='';try{const value=await readSurgeryArchive(id);if(token===request)archive=value;}catch(e){if(token===request)error=e instanceof Error?e.message:'Could not load surgery archive.';}finally{if(token===request)loading=false;}}
  onDestroy(()=>request+=1);
  $: topics=archive?SURGERY_SYLLABUS.map(definition=>({definition,progress:archive!.state.topics[definition.id]})):[];
  $: filtered=topics.filter(t=>(block==='all'||t.definition.block===block)&&`${t.definition.id} ${t.definition.title} ${t.progress.notes}`.toLowerCase().includes(search.toLowerCase()));
  $: assessed=topics.filter(t=>t.progress.status!=='unassessed').length;
  $: first=archive?.progress?passCount(archive.progress,'first'):0;
  $: second=archive?.progress?passCount(archive.progress,'second'):0;
  $: openGaps=topics.reduce((n,t)=>n+t.progress.gaps.filter(g=>!g.resolvedAt).length,0);
  $: time=archive?groupSurgerySessionsByDay(archive.sessions).reduce((n,day)=>n+day.durationSeconds,0):0;
  $: frozenTimer=archive?.state.activeStudyTimer?timerElapsedSeconds(archive.state.activeStudyTimer,new Date(archive.state.updatedAt).getTime()):0;
  $: ankiStats=archive?summarizeAnkiGapCards(archive.cards):null;
  function download(){if(!archive)return;const data={kind:'trackr-surgery-backup',exportedAt:new Date().toISOString(),state:archive.state,sessions:archive.sessions,retentionCards:archive.cards,reviews:archive.reviews,simulations:archive.simulations,...(archive.config&&archive.progress?{studyPlan:{config:archive.config,progress:archive.progress}}:{})};const url=URL.createObjectURL(new Blob([JSON.stringify(data,null,2)],{type:'application/json'}));const a=document.createElement('a');a.href=url;a.download='trackr-surgery-frozen-backup.json';a.click();URL.revokeObjectURL(url);}
</script>
<svelte:head><title>Surgery · Passed · Trackr</title></svelte:head>
<div class="archive-shell">
  <header><div><p class="eyebrow">SURGERY · STATE EXAM</p><h1>Passed.</h1><p>Your surgery history is preserved. Timers, countdowns and syncing are stopped.</p></div><span class="badge">Frozen archive</span></header>
  {#if error}<p class="error" role="alert">{error}</p><button on:click={()=>uid&&load(uid)}>Retry</button>{/if}
  {#if loading}<p>Loading your archive…</p>{:else if !uid}<p>Sign in to view your surgery history.</p>{:else if archive}
    <section class="stats"><article><span>Assessed</span><strong>{assessed}<small> / 196</small></strong></article><article><span>First pass</span><strong>{first}<small> / 196</small></strong></article><article><span>Second pass</span><strong>{second}<small> / 196</small></strong></article><article><span>Recorded study time</span><strong>{formatStudyDuration(time)}</strong></article><article><span>Recorded gaps</span><strong>{openGaps}</strong></article><article><span>Retention cards</span><strong>{archive.cards.length}</strong></article></section>
    {#if archive.state.activeStudyTimer}<p class="muted">Unfinished timer preserved at its last saved update: {formatStudyDuration(frozenTimer)}. It is stopped in this archive.</p>{/if}
    <section class="panel"><h2>Progress over time</h2>{#if archive.sessions.length||archive.progress}<SurgeryProgressChart sessions={archive.sessions} planProgress={archive.progress} reviewEvents={archive.reviews}/>{:else}<p>No recorded study sessions.</p>{/if}</section>
    <nav aria-label="Surgery archive views">{#each ['topics','cards','history','plan'] as name}<button class:active={tab===name} on:click={()=>tab=name}>{name[0].toUpperCase()+name.slice(1)}</button>{/each}<button class="export" on:click={download}>Export full backup</button></nav>
    {#if tab==='topics'}<section class="panel"><h2>Knowledge map</h2><div class="heatmap">{#each topics as t}<a class={`mastery-${t.progress.mastery}`} href={`#surgery-${t.definition.id}`} title={`${t.definition.id} · ${t.definition.title}`} on:click={()=>{search='';block='all';}}>{t.definition.id.replace('TO','').replace('-','·')}</a>{/each}</div><div class="filters"><input aria-label="Search surgery topics" bind:value={search} placeholder="Search ID, title or notes"/><select aria-label="Surgery question group" bind:value={block}><option value="all">All groups</option>{#each SURGERY_BLOCKS as group}<option value={group.id}>{group.label}</option>{/each}</select></div>
      {#each filtered as t}<details id={`surgery-${t.definition.id}`}><summary><b>{t.definition.id}</b><span>{t.definition.title}</span><small>Mastery {t.progress.mastery}/4</small></summary><div class="detail"><p>Confidence {t.progress.confidence}/4 · {t.progress.correct}/{t.progress.attempts} answers correct · {t.progress.status}</p><p>First pass: {archive.progress?.topics[t.definition.id]?.firstPassCompletedAt?.slice(0,10)??'Not recorded'} · Second pass: {archive.progress?.topics[t.definition.id]?.secondPassCompletedAt?.slice(0,10)??'Not recorded'}</p>{#if t.progress.notes}<p class="preserve">{t.progress.notes}</p>{/if}{#each t.progress.gaps as gap}<p class:resolved={!!gap.resolvedAt}>{gap.resolvedAt?'Resolved':'Open'} · {gap.text}</p>{/each}</div></details>{/each}</section>
    {:else if tab==='cards'}<section class="panel"><h2>Saved retention cards</h2>{#if ankiStats}<AnkiStatsPanel stats={ankiStats}/>{/if}{#each archive.cards as card}<details><summary><b>{card.topicId}</b><span>{card.front}</span></summary><div class="detail preserve">{card.back}</div></details>{/each}{#if !archive.cards.length}<p>No saved cards.</p>{/if}</section>
    {:else if tab==='history'}<section class="panel"><h2>Study sessions</h2>{#each [...archive.sessions].reverse() as session}<details><summary><b>{session.date.slice(0,10)}</b><span>{session.label}</span><small>{session.questions} questions</small></summary><div class="detail">{session.topicIds?.join(', ')??''}{#if session.durationSeconds}<p>{formatStudyDuration(session.durationSeconds)}</p>{/if}</div></details>{/each}<h2>Recall history</h2>{#each [...archive.reviews].sort((a,b)=>b.reviewedAt.localeCompare(a.reviewedAt)) as review}<p>{review.reviewedAt.slice(0,10)} · {review.topicId} · {review.outcome}{#if review.notes} · {review.notes}{/if}</p>{/each}<h2>Oral simulations</h2>{#each archive.simulations as simulation}<p>{simulation.date.slice(0,10)} · {simulation.outcome} · {simulation.topicIds.join(', ')}{#if simulation.notes} · {simulation.notes}{/if}</p>{/each}</section>
    {:else}<section class="panel"><h2>{archive.config?.name??'Surgery study plan'}</h2>{#if archive.config}<p>Exam date: {archive.config.examDate} · Plan started: {archive.config.planStartDate}</p>{#each archive.config.phases as phase}<p><b>{phase.name}</b> · {phase.startDate} – {phase.endDate} · target {phase.target}</p>{/each}<h3>Buffer objectives</h3>{#each archive.config.bufferObjectives as objective}<p>{objective.completedAt?'✓':'○'} {objective.title}{#if objective.notes} · {objective.notes}{/if}</p>{/each}{:else}<p>No saved plan.</p>{/if}</section>{/if}
  {/if}
</div>
<style>
.archive-shell{max-width:1450px;margin:auto;padding:2rem 1rem 5rem;color:#eef0f7}header{display:flex;justify-content:space-between;align-items:center;gap:1rem;margin-bottom:2rem}.eyebrow{font-size:.8rem;letter-spacing:.14em;color:#aab4c8}h1{font-size:clamp(3rem,7vw,5rem);margin:.2rem 0;line-height:1}header p{color:#a7afc0}.badge{border:1px solid #436a5d;color:#a8ddc1;background:#192a25;padding:.7rem 1rem;border-radius:999px;white-space:nowrap}.stats{display:grid;grid-template-columns:repeat(3,1fr);gap:.8rem}.stats article,.panel{background:#141923;border:1px solid #2a3242;border-radius:16px;padding:1.2rem}.stats span{display:block;color:#a7afc0;font-size:.9rem}.stats strong{display:block;font-size:2rem;margin-top:.5rem}.stats small{font-size:1rem;color:#a7afc0}.panel{margin-top:1rem}h2{font-size:1.3rem;margin-top:0}.heatmap{display:grid;grid-template-columns:repeat(auto-fill,minmax(45px,1fr));gap:5px;margin:1rem 0}.heatmap a{padding:.6rem .2rem;text-align:center;border-radius:7px;color:#eef0f7;text-decoration:none;font-size:.8rem;background:#282d37}.heatmap .mastery-1{background:#62394d}.heatmap .mastery-2{background:#9a633f}.heatmap .mastery-3{background:#61744d}.heatmap .mastery-4{background:#3f8f71}nav{display:flex;gap:.5rem;flex-wrap:wrap;margin-top:1.5rem}button,input,select{font:inherit;background:#1c2230;color:#eef0f7;border:1px solid #354158;border-radius:9px;padding:.65rem .85rem;min-height:44px;box-sizing:border-box}button{cursor:pointer}button.active{background:#4656a8}.export{margin-left:auto}.filters{display:flex;gap:.5rem;margin:1rem 0}.filters input{flex:1;min-width:0}details{border-top:1px solid #2e3748;scroll-margin-top:100px}summary{display:flex;align-items:center;gap:1rem;padding:1rem .25rem;cursor:pointer;font-size:.95rem}summary span{flex:1}summary small{color:#a7afc0}.detail{padding:.3rem 1rem 1rem;color:#bcc4d5}.preserve{white-space:pre-wrap}.resolved{color:#8aa99b}.muted{color:#a7afc0}.error{color:#ffb0b9}@media(max-width:700px){.archive-shell{padding:1rem .25rem 5rem}header{align-items:start;flex-direction:column}.stats{grid-template-columns:repeat(2,1fr)}.stats strong{font-size:1.6rem}.export{margin-left:0}.filters{flex-wrap:wrap}.filters input{flex-basis:100%}summary{flex-wrap:wrap;gap:.5rem}summary small{width:100%}}
</style>
